project:
  type: website
  output-dir: docs

website:
  title: "Carter McMahon"
  navbar:
    left:
      - text: "Projects"
        file: index.qmd
      - about.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

